### ISSUE TITLE
Test issue in Acmesolver

### ISSUE THREAD

**Issue by juan131** [bitnami/bitnami-docker-acmesolver#4]
**Description**

Test

**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by pablogalegoc** [comment]
This is a response

**Comment by juan131** [comment]
I consider this ticket solved
